
dist: xenial

language: python 
python: 
- "3.6"
env: 
- DJANGO=2.0 DB=postgres
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - cd decide
  - python manage.py migrate
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
  - coverage xml
  - python-codacy-coverage -r coverage.xml
